#!/bin/bash

if [ "x${UCVM_INSTALL_PATH}" != "x" ]; then
  if [ -d ${UCVM_INSTALL_PATH}/model/cvmhsgbn/lib ]; then
     source ${UCVM_INSTALL_PATH}/conf/ucvm_env.sh
     ./accepttest
    exit
  fi
fi

env DYLD_LIBRARY_PATH=../src LD_LIBRARY_PATH=../src ./accepttest
