#!/bin/bash

if [[ -z "${UCVM_INSTALL_PATH}" ]]; then
  if [[ -f "${UCVM_INSTALL_PATH}/model/cvmhsgbn/lib" ]]; then
    env DYLD_LIBRARY_PATH=${UCVM_INSTALL_PATH}/model/cvmhsgbn/lib ./unittest
    exit
  fi
fi

env DYLD_LIBRARY_PATH=../src LD_LIBRARY_PATH=../src ./unittest
